hacknus/serial-monitor-rust

src/data.rs, src/gui.rs
This PR removes return statements at the end of a block.
=> Remove unneeded `return` statement

src/gui.rs, src/main.rs, src/serial.rs
=> Remove unnecessary clone

src/main.rs
Now, this is not a simple clippy fix. I think you want to split a `&str` with `':'` and `','` and take out `&str`s that represent `f32`. This PR should do that. Here is a set of simple tests I used. If I am missing something, please let me know.
```rust
#[test]
fn test_split() {
let input = "foo: bar, baz, qux: -0.1, 0.2, -0.3";
let expected_output = vec!["-0.1", "0.2", "-0.3"];
let actual_output = split(input);
assert_eq!(expected_output, actual_output);
}
#[test]
fn test_split_2() {
let input = "foo:bar,baz,qux:-0.1,0.2,-0.3";
let expected_output = vec!["-0.1", "0.2", "-0.3"];
let actual_output = split(input);
assert_eq!(expected_output, actual_output);
}
```
I think we should parse in this function and return `Vec<f32>` instead of `Vec<&str>`. But that requires modification in main. …
=> Refactor `fn split`

src/main.rs
This function can fail if we fail to set up a graphics context.
=> Handle Result

src/gui.rs
This should do the same as the original code. 
But doesn't `window` always end up as `0` because `self.plotting_range` is set to `-1` and never gets modified?
=> Clean up if statements in gui.rs

src/serial.rs
This fixes #27.
Since the return type of the function `serial_write` has been changed to `Result`, we must use it when calling the function. Please review carefully line 154 ~ 161. Unless I have misunderstood your intention, we do not need to use `std::str::from_utf8(output)`. Instead, we can directly pass the `cmd` variable, which is a `String`.
=> Refactor serial_write

src/gui.rs, src/main.rs
I believe `prefs_key` is shared between `main` and `gui`. To ensure consistency and avoid unintended modifications, this PR proposes declaring prefs_key as a `constant` in main.
Furthermore, this PR introduces a new function called `load_gui_settings`. This function is designed to handle loading settings specific to the GUI component. By encapsulating this functionality in a separate function, we can improve the modularity and reusability.
=> Refactor GuiSettingsContainer load/save

src/serial.rs
In my opinion, `dev_is_con` is not a very descriptive name for a variable. A more readable approach might be to directly call `devices.contains(&device)` instead. This would make the code clearer and easier to understand.
=> Improve clarity by directly calling `devices.contains(&device)`

src/gui.rs
This pull request makes `baud_rates` a constant outside the function, so that it is only allocated once and reused on each call to the function. By doing this, we ensure that `BAUD_RATES` is only allocated once, instead of on each call to the function, resulting in improved performance.
=> Avoid unnecessary reallocation of Vec

src/gui.rs
The variable `text_style` is not used elsewhere in the code. We can replace it with `egui::TextStyle::Body`.
Using constants can improve code readability and reduce the potential for mistakes, as it makes it clearer what value is being used in a particular context.
=> Remove unnecessary variable

src/gui.rs, src/main.rs, src/serial.rs
This pull request replaces `device_lock: Arc<RwLock<String>>` and `baud_lock: Arc<RwLock<u32>>` with `device_lock: Arc<RwLock<Device>>`.
=> Refactor device name and baud rate handling

src/gui.rs
I think that `Vec<Vec<PlotPoint>>` is more readable and better communicates the intention compared to `Vec<Vec<[f64; 2]>>`. Using `PlotPoint` instead of `[f64; 2]` adds more context to the data structure and makes it clearer that the elements are meant to represent points in a plot.
=> Use `PlotPoint` instead of `[f64; 2]`

src/gui.rs, src/io.rs, src/main.rs
I propose creating a new struct called `CsvOptions` that contains a set of options for saving data to a CSV file. Using `CsvOptions` will improve the readability of the code and better communicate the intention of the options being passed compared to using a tuple like `(PathBuf, bool)`. The struct contains the necessary fields to specify the path to the CSV file and whether timestamps should be formatted as absolute or relative times.
=> Add `CsvOptions` struct for improved readability

src/gui.rs, src/serial.rs
This adds the ability to display multiple plots, where each column can be toggled individually per plot, potentially closing #82.
Additionally, it adds interactive resize using the separator between the plots and the serial monitor.
The resize code might not be the most pretty implementation, but I was unable to find any example of this in the `egui` examples. Therefore this commit also includes a small refactor of how heights are computed.
One thing left out of this commit, is the ability to save plots of any but the first plot.
=> Add option to display multiple plots, and resize the plot panel

src/gui.rs, src/main.rs
this addresses the syncing idea brought up in #102
=> sync the frame updates to data packets received (and parsed)

CHANGELOG.md, src/custom_highlighter.rs, src/gui.rs, src/main.rs, src/serial.rs
Hello there !
Even if I'm I huge fan of minicom I was looking for a serial monitor that allow me to perform sentence highlightment.
I find you plots feature interesting even if i haven't use it so far but i'm sure I will.
I'm still not a rust Guru and this is still work in progress but i wanted to share it with you and get your opinions on it.
I have concern on how much the sentence search using regex will load the CPU. 
For sure it will be possible to save previously found sentence and only doing the search process on new lines.
Also I was wondering if 
- it is possible in egui to not perform a full reload of the "console_scroll_area" to preserve CPU
- to reduce FPS when no new frames was available and to force a repaint_request on RX/TX messages
Here is some capture i have done : 
ps : …
=> Sentence highlightment

CHANGELOG.md, Cargo.lock, Cargo.toml, src/color_picker.rs, src/custom_highlighter.rs, src/gui.rs, src/main.rs, src/serial.rs
the log area looks a bit crowded because of the filenames and function names, but it is much more useful go through for debugging. Especially since also the egui logs are now displayed, if `Debug` is selected in the filter.
=> implement egui_logger

.github/workflows/deployment.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, build.rs, src/gui.rs, src/main.rs, src/settings_window.rs, src/update.rs
The user can check for updates and the application will automatically download the latest release from github.
=> Add possibility to Self update

CHANGELOG.md, README.md, src/gui.rs, src/main.rs
This should fix #112 and #115.
=> Fix sample rate issue

README.md
Compiling from source on Debian 14 failed with some errors, amongst them:
```The system library `libudev` required by crate `libudev-sys` was not found.```
After installing `libudev-dev` the error went away and the serial monitor compiled just fine. It hence seems to make sense to add this to the readme as build dependency.
=> Added required package to build from source on Linux.

src/data.rs
When receiving only a single column of data, no graph would ever show up.
This was due to the graph display data structure only being initialized when the number of datasets changes.  However, the dataset attribute is populated with one entry by default, so when receiving a single column of data, the graph initialization never happens.
Fix this by initializing the dataset structure to be empty by default.
This bug was introduced in PR #119.
=> Fix single column graph display

CHANGELOG.md, src/main.rs, src/settings_window.rs
Hi,
I noticed that the theme preference is not being restored correctly.  This PR contains the necessary changes to make it work :)
---
Using `set_visuals(Visuals::dark())` in `main()` somehow interfered badly with the theme switching code such that a light theme was not restored properly.
Instead, the correct function to set the theme on startup is `set_theme()` and we should pass in the saved preference instead of hard-coding dark-mode.
=> Fix theme preference not being restored correctly
